extern const GeoLayout nether_geo[];
extern Lights1 nether_obsidian_lights;
extern Lights1 nether_portal_lights;
extern u8 nether_obsidian_ci4[];
extern u8 nether_obsidian_pal_rgba16[];
extern u8 nether_nether_portal_base_rgba32[];
extern Vtx nether_Nether_Portal_mesh_layer_4_vtx_0[92];
extern Gfx nether_Nether_Portal_mesh_layer_4_tri_0[];
extern Vtx nether_Nether_Portal_mesh_layer_5_vtx_0[8];
extern Gfx nether_Nether_Portal_mesh_layer_5_tri_0[];
extern Gfx mat_nether_obsidian[];
extern Gfx mat_revert_nether_obsidian[];
extern Gfx mat_nether_portal[];
extern Gfx mat_revert_nether_portal[];
extern Gfx nether_Nether_Portal_mesh_layer_4[];
extern Gfx nether_Nether_Portal_mesh_layer_5[];
extern Gfx nether_material_revert_render_settings[];
