#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "DRExplosion/geo.inc.c"
#include "nether/geo.inc.c"

#include "psychiatristsit/geo.inc.c"
#include "zero/geo.inc.c"
#include "zero_walk/geo.inc.c"
#include "zero_sit/geo.inc.c"
#include "psych_stand/geo.inc.c"
#include "psych_walk/geo.inc.c"
#include "katana_a_button/geo.inc.c"
#include "psych_killrock/geo.inc.c"
#include "sophie/geo.inc.c"
#include "psych_getneedle/geo.inc.c"
#include "psych_walkneedle/geo.inc.c"
#include "psych_inject/geo.inc.c"
#include "frisk/geo.inc.c"
#include "building_ext/geo.inc.c"
#include "hallway/geo.inc.c"
#include "pikmin/geo.inc.c"
#include "fake_mario/geo.inc.c"