#include "src/game/envfx_snow.h"

const GeoLayout pikmin_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pikmin_000_offset_bottom_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_001_Chest_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, pikmin_000_offset_001_Chest_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_displaylist_Head_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_ALPHA, pikmin_000_displaylist_Head_mesh_layer_4),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_003_LShoulder_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pikmin_000_offset_003_LShoulder_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_004_LArm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, pikmin_000_offset_004_LArm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_displaylist_003_LHand_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_displaylist_003_LHand_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_006_Rshoulder_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pikmin_000_offset_006_Rshoulder_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_007_RArm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, pikmin_000_offset_007_RArm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_displaylist_004_Rhand_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_displaylist_004_Rhand_mesh_layer_1),
											GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_009_LThigh_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pikmin_000_offset_009_LThigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_010_LLeg_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, pikmin_000_offset_010_LLeg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_011_LFoot_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, pikmin_000_offset_011_LFoot_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_012_RThigh_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pikmin_000_offset_012_RThigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_offset_013_RLeg_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, pikmin_000_offset_013_RLeg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_displaylist_005_RFoot_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_000_displaylist_005_RFoot_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pikmin_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, pikmin_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
