extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_bg_psychiatrist_0_rgba16[];
extern u8 bob_dl_fireplacedefault_rgba16[];
extern u8 bob_dl_texbox_arrow_ia4[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[256];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_fireplace_mesh_layer_4_vtx_0[4];
extern Gfx bob_dl_fireplace_mesh_layer_4_tri_0[];
extern Vtx bob_dl_textbox_1_002_mesh_layer_5_vtx_0[32];
extern Gfx bob_dl_textbox_1_002_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_010_layer5[];
extern Gfx mat_revert_bob_dl_f3dlite_material_010_layer5[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_fireplace_mesh_layer_4[];
extern Gfx bob_dl_textbox_1_002_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
